const db = require('../../config/database');

exports.seed = async (knex) => {
  // First, delete existing entries
  await knex('wait_times').del();
  await knex('mobile_units').del();
  await knex('routes').del();
  await knex('facility_archives').del();
  await knex('facilities').del();
  await knex('users').del();

  // Insert test users
  const users = await knex('users').insert([
    {
      email: 'patient@example.com',
      password: '$2a$10$kJ5BkCzUYpKJMKVnYPqN4OJq0WFy7p5qyHvJkJkJkJkJ', // bcrypt hashed 'password123'
      full_name: 'Test Patient',
      user_type: 'patient',
      phone: '+91-9876543210',
      is_active: true,
    },
    {
      email: 'operator@example.com',
      password: '$2a$10$kJ5BkCzUYpKJMKVnYPqN4OJq0WFy7p5qyHvJkJkJkJkJ',
      full_name: 'Test Operator',
      user_type: 'operator',
      phone: '+91-9876543211',
      is_active: true,
    },
    {
      email: 'admin@example.com',
      password: '$2a$10$kJ5BkCzUYpKJMKVnYPqN4OJq0WFy7p5qyHvJkJkJkJkJ',
      full_name: 'Test Admin',
      user_type: 'admin',
      phone: '+91-9876543212',
      is_active: true,
    },
  ]).returning('id');

  // Facilities data from index.html
  const facilities = [
    {
      name: 'AIIMS New Delhi',
      type: 'hospital',
      address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi',
      latitude: 28.5672,
      longitude: 77.2100,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2100 28.5672)')"),
      phone: '+91-11-26588500',
      description: 'Premier public medical institution offering comprehensive multi-speciality tertiary care.',
      specialties: JSON.stringify(['Emergency', 'Cardiology', 'Neurology', 'Oncology', 'Paediatrics']),
      beds: 2478,
      rating: 4.8,
      is_open: true,
    },
    {
      name: 'Apollo Clinic Saket',
      type: 'clinic',
      address: 'M-4, M Block Market, Saket, New Delhi',
      latitude: 28.5213,
      longitude: 77.2040,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2040 28.5213)')"),
      phone: '+91-11-71001066',
      description: 'Modern multi-speciality outpatient clinic with diagnostic services.',
      specialties: JSON.stringify(['General', 'Cardiology', 'Gynaecology']),
      beds: null,
      rating: 4.5,
      is_open: true,
    },
    {
      name: 'Safdarjung Hospital',
      type: 'hospital',
      address: 'Ansari Nagar West, New Delhi',
      latitude: 28.5693,
      longitude: 77.2017,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2017 28.5693)')"),
      phone: '+91-11-26707444',
      description: 'Large government hospital and medical college with round-the-clock emergency services.',
      specialties: JSON.stringify(['Emergency', 'Orthopaedics', 'General', 'Gynaecology']),
      beds: 1531,
      rating: 4.0,
      is_open: true,
    },
    {
      name: 'Mobile Unit Alpha — Connaught Place',
      type: 'mobile',
      address: 'In transit near Connaught Place',
      latitude: 28.6315,
      longitude: 77.2167,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2167 28.6315)')"),
      phone: '+91-98100-00001',
      description: 'Fully equipped emergency response mobile unit serving Central Delhi.',
      specialties: JSON.stringify(['Emergency', 'General']),
      beds: null,
      rating: 4.6,
      is_open: true,
    },
    {
      name: 'Mobile Unit Beta — Lajpat Nagar',
      type: 'mobile',
      address: 'Patrolling Lajpat Nagar sector',
      latitude: 28.5677,
      longitude: 77.2434,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2434 28.5677)')"),
      phone: '+91-98100-00002',
      description: 'Community health mobile unit focused on paediatrics and primary care.',
      specialties: JSON.stringify(['General', 'Paediatrics']),
      beds: null,
      rating: 4.4,
      is_open: true,
    },
    {
      name: 'Max Smart Super Speciality — Saket',
      type: 'clinic',
      address: 'Press Enclave Marg, Saket',
      latitude: 28.5245,
      longitude: 77.2132,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2132 28.5245)')"),
      phone: '+91-11-26515050',
      description: 'Super-speciality hospital delivering advanced cardiac, neuro and onco care.',
      specialties: JSON.stringify(['Cardiology', 'Neurology', 'Orthopaedics', 'Oncology']),
      beds: null,
      rating: 4.7,
      is_open: true,
    },
    {
      name: 'Apollo Pharmacy — Hauz Khas',
      type: 'pharma',
      address: 'Hauz Khas Village, New Delhi',
      latitude: 28.5535,
      longitude: 77.2008,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2008 28.5535)')"),
      phone: '+91-1800-419-0000',
      description: '24-hour pharmacy with full medicine inventory and home delivery.',
      specialties: JSON.stringify(['General']),
      beds: null,
      rating: 4.3,
      is_open: true,
    },
    {
      name: 'RML Hospital',
      type: 'hospital',
      address: 'Baba Kharak Singh Marg, New Delhi',
      latitude: 28.6255,
      longitude: 77.2020,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2020 28.6255)')"),
      phone: '+91-11-23404390',
      description: 'Major government hospital providing free care to Delhi residents.',
      specialties: JSON.stringify(['Emergency', 'General', 'Paediatrics']),
      beds: 1533,
      rating: 3.9,
      is_open: true,
    },
    {
      name: 'SRL Diagnostics — Vasant Kunj',
      type: 'clinic',
      address: 'DDA Market, Vasant Kunj',
      latitude: 28.5186,
      longitude: 77.1565,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.1565 28.5186)')"),
      phone: '+91-11-39027777',
      description: 'Full-service diagnostic lab with home sample collection.',
      specialties: JSON.stringify(['General']),
      beds: null,
      rating: 4.2,
      is_open: true,
    },
    {
      name: 'Mobile Unit Gamma — Dwarka',
      type: 'mobile',
      address: 'Patrolling Dwarka Sector 10',
      latitude: 28.5815,
      longitude: 77.0484,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.0484 28.5815)')"),
      phone: '+91-98100-00003',
      description: 'West Delhi rapid response mobile unit servicing Dwarka sectors.',
      specialties: JSON.stringify(['Emergency', 'General']),
      beds: null,
      rating: 4.5,
      is_open: true,
    },
    {
      name: 'Fortis Hospital — Vasant Kunj',
      type: 'hospital',
      address: 'B-22, Vasant Kunj, New Delhi',
      latitude: 28.5200,
      longitude: 77.1520,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.1520 28.5200)')"),
      phone: '+91-11-42776222',
      description: 'Multi-speciality private hospital with advanced cardiac and neuro departments.',
      specialties: JSON.stringify(['Cardiology', 'Neurology', 'Orthopaedics']),
      beds: 262,
      rating: 4.6,
      is_open: true,
    },
    {
      name: 'CGHS Dispensary — Karol Bagh',
      type: 'clinic',
      address: 'Karol Bagh, New Delhi',
      latitude: 28.6518,
      longitude: 77.1900,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.1900 28.6518)')"),
      phone: '+91-11-25741234',
      description: 'Government health scheme dispensary serving Karol Bagh locality.',
      specialties: JSON.stringify(['General', 'Paediatrics']),
      beds: null,
      rating: 3.8,
      is_open: true,
    },
    {
      name: 'MedPlus — Lajpat Nagar',
      type: 'pharma',
      address: 'Central Market, Lajpat Nagar II',
      latitude: 28.5640,
      longitude: 77.2410,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2410 28.5640)')"),
      phone: '+91-40-67676767',
      description: 'Well-stocked pharmacy chain outlet with prescription and OTC medicines.',
      specialties: JSON.stringify(['General']),
      beds: null,
      rating: 4.1,
      is_open: true,
    },
    {
      name: 'Indraprastha Apollo — Sarita Vihar',
      type: 'clinic',
      address: 'Mathura Road, Sarita Vihar',
      latitude: 28.5355,
      longitude: 77.2805,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2805 28.5355)')"),
      phone: '+91-11-71791090',
      description: 'Flagship Apollo hospital with comprehensive speciality services and emergency care.',
      specialties: JSON.stringify(['Emergency', 'Cardiology', 'Gynaecology', 'Oncology']),
      beds: 710,
      rating: 4.8,
      is_open: true,
    },
    {
      name: 'Mobile Unit Delta — Rohini',
      type: 'mobile',
      address: 'Near Rohini Sector 3 Metro',
      latitude: 28.7232,
      longitude: 77.1218,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.1218 28.7232)')"),
      phone: '+91-98100-00004',
      description: 'North Delhi community mobile unit; currently on maintenance break until 14:00.',
      specialties: JSON.stringify(['General', 'Paediatrics']),
      beds: null,
      rating: 4.3,
      is_open: false,
    },
    {
      name: 'GTB Hospital — Shahdara',
      type: 'hospital',
      address: 'Dilshad Garden, Shahdara, Delhi',
      latitude: 28.6783,
      longitude: 77.3059,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.3059 28.6783)')"),
      phone: '+91-11-22582626',
      description: 'Busy public hospital serving East Delhi with 24×7 trauma and casualty.',
      specialties: JSON.stringify(['Emergency', 'General', 'Orthopaedics']),
      beds: 1500,
      rating: 3.7,
      is_open: true,
    },
    {
      name: 'Medanta OPD — Gurugram',
      type: 'clinic',
      address: 'Sector 38, Gurugram, Haryana',
      latitude: 28.4596,
      longitude: 77.0266,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.0266 28.4596)')"),
      phone: '+91-124-4141414',
      description: 'Premium multi-speciality outpatient facility of Medanta — The Medicity.',
      specialties: JSON.stringify(['Cardiology', 'Neurology', 'Gynaecology', 'Oncology']),
      beds: null,
      rating: 4.9,
      is_open: true,
    },
    {
      name: 'Guardian Pharmacy — Rohini',
      type: 'pharma',
      address: 'Sector 11, Rohini, New Delhi',
      latitude: 28.7155,
      longitude: 77.1276,
      geometry: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.1276 28.7155)')"),
      phone: '+91-11-27562000',
      description: '24-hour pharmacy with full stock and cold-chain storage for insulin.',
      specialties: JSON.stringify(['General']),
      beds: null,
      rating: 4.0,
      is_open: true,
    },
  ];

  const facilityIds = await knex('facilities').insert(facilities).returning('id');

  // Insert initial wait times for each facility
  const waitTimes = facilityIds.map((id, index) => ({
    facility_id: id,
    wait_time_minutes: [42, 18, 65, 5, 8, 25, 3, 55, 10, 6, 30, 22, 2, 20, 7, 70, 15, 5][index],
    status: [42, 65, 70].includes([42, 18, 65, 5, 8, 25, 3, 55, 10, 6, 30, 22, 2, 20, 7, 70, 15, 5][index]) ? 'high' : 'normal',
    patients_waiting: Math.floor(Math.random() * 20) + 5,
  }));

  await knex('wait_times').insert(waitTimes);

  // Insert mobile unit locations
  const mobileUnits = [
    { facility_id: facilityIds[3], latitude: 28.6315, longitude: 77.2167, location: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2167 28.6315)')"), status: 'active' },
    { facility_id: facilityIds[4], latitude: 28.5677, longitude: 77.2434, location: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.2434 28.5677)')"), status: 'active' },
    { facility_id: facilityIds[9], latitude: 28.5815, longitude: 77.0484, location: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.0484 28.5815)')"), status: 'active' },
    { facility_id: facilityIds[15], latitude: 28.7232, longitude: 77.1218, location: knex.raw("ST_GeogFromText('SRID=4326;POINT(77.1218 28.7232)')"), status: 'maintenance' },
  ];

  await knex('mobile_units').insert(mobileUnits);

  console.log('✅ Seeding complete: 18 facilities, 3 users, wait times, and mobile units inserted');
};
